spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mysql://localhost:3306/cafe?useSSL=false&allowPublicKeyRetrieval=true&forceConnectionTimeZoneToSession=true&connectionTimezone=Asia/Seoul"
    username: root
    password: root
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        create_empty_composites:
          enabled: true
